version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.8

    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d7:cb:f6:47:2c:68:d0:78:a6:a6:34:ef:dc:31:d5:9b"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # clean up run cache
      - run: rm -rf _terraform
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
      - run: ./build/clean.sh